<?php
namespace ADOdb\Driver\PDO;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-22 at 17:57:46.
 */
class DriverTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Driver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getAbstractMock("\ADOdb\Driver\PDO\Driver");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
