<?php
namespace ADOdb\Driver\PDO;


require_once '/home/likewise-open/OFICINAS/dario.mancuso/htdocs/adodb/ADOdb/ADOdb.php';

/**
 * Test class for FieldObject.
 * Generated by PHPUnit on 2011-09-14 at 15:26:23.
 */
class FieldObjectTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FieldObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FieldObject;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
