<?php
namespace ADOdb;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-22 at 17:57:47.
 */
class ConnectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Connection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Connection('sqlite::memory:');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testConnect()
    {
        $this->object->connect();
        return $this->object;
    }

    /**
     * @param Connection $db
     * @depends testConnect
     */
    public function testExecute(Connection $db)
    {
        $table = uniqid('table_');
        $db->execute("CREATE TABLE $table (id int, display varchar(100));");
        $db->execute("INSERT INTO $table VALUES (1, 'a'), (2, 'b'), (3, 'c'), (4, 'd');");
        return array($table, $db);
    }

    /**
     * @param $params
     * @depends testExecute
     */
    public function testGetAll(array $params)
    {
        list($table, $db) = $params;
        $results = $db->getAll("SELECT * FROM $table;");
        $this->assertEquals(4, count($results));
    }
}