<?php
namespace ADOdb;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-22 at 17:57:48.
 */
class DataSourceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DataSource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DataSource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
